server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location / {
        return 302 /netflix/;
    }

    location /netflix/ {
        index index.html;
        try_files $uri $uri/ =404;
    }

    location /netflix/videos/ {
        types {
            video/mp4 mp4;
        }
        add_header Accept-Ranges bytes;
    }
}
