[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1001]
type=endpoint
context=interno
disallow=all
allow=ulaw,alaw
auth=auth1001
aors=1001

[auth1001]
type=auth
auth_type=userpass
username=1001
password=clave1001

[1001]
type=aor
max_contacts=1

[1002]
type=endpoint
context=interno
disallow=all
allow=ulaw,alaw
auth=auth1002
aors=1002

[auth1002]
type=auth
auth_type=userpass
username=1002
password=clave1002

[1002]
type=aor
max_contacts=1
